#!/usr/bin/env bash
# collect_status.sh — Gather LinuxCNC host + machine status and commit it to the repo.
#
# Runs on the LinuxCNC control PC (Dell OptiPlex 7050, Debian 13, PREEMPT-RT).
# Produces:
#   status/host_status.md    human-readable Markdown
#   status/host_status.json  machine-readable JSON
# Commits + pushes both when they change.
#
# Invoked by systemd unit  mazak-host-status.service  on a 15-minute timer.
# Safe to run by hand:  bash scripts/host_status/collect_status.sh
#
# Requirements on the host:
#   - git configured for the retrofit repo with push credentials (SSH key or gh auth)
#   - jq installed
#   - halcmd on PATH (LinuxCNC install provides it)
#   - Optional: mesaflash on PATH  (for Mesa board ping)
#
# The script is intentionally READ-ONLY toward LinuxCNC — it never writes HAL pins,
# never starts/stops the machine, never invokes anything that could move an axis.

set -uo pipefail

# ---------- config ----------
REPO_DIR="${MAZAK_REPO_DIR:-/home/andy/mazak-vqc20-linuxcnc-retrofit}"
MESA_IP="${MAZAK_MESA_IP:-192.168.1.121}"
BRANCH="${MAZAK_STATUS_BRANCH:-main}"
STATUS_DIR="status"
MD_FILE="${STATUS_DIR}/host_status.md"
JSON_FILE="${STATUS_DIR}/host_status.json"

# Signals to sample from halcmd if LinuxCNC is running. Extend as bring-up proceeds.
HAL_SIGNALS=(
    "estop-ext"
    "machine-is-on"
    "spindle.0.on"
    "axis.x.pos-fb"
    "axis.y.pos-fb"
    "axis.z.pos-fb"
)

# ---------- helpers ----------
ts_iso()   { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
ts_human() { date +"%Y-%m-%d %H:%M:%S %Z"; }

json_escape() {
    # minimal escape for embedding a shell string into JSON
    python3 -c 'import json,sys; print(json.dumps(sys.stdin.read().rstrip()))'
}

have() { command -v "$1" >/dev/null 2>&1; }

# ---------- collect ----------
HOST=$(hostname)
KERNEL=$(uname -r)
OS_PRETTY=$(. /etc/os-release 2>/dev/null; echo "${PRETTY_NAME:-unknown}")
UPTIME=$(uptime -p 2>/dev/null || uptime)
LOAD=$(awk '{print $1", "$2", "$3}' /proc/loadavg)
MEM_LINE=$(free -h | awk '/^Mem:/ {print $3" used / "$2" total"}')
DISK_LINE=$(df -h / | awk 'NR==2 {print $3" used / "$2" total ("$5" full)"}')

# LinuxCNC process check
LCNC_RUNNING="no"
LCNC_PIDS=""
if pgrep -x linuxcnc >/dev/null 2>&1 || pgrep -x milltask >/dev/null 2>&1; then
    LCNC_RUNNING="yes"
    LCNC_PIDS=$(pgrep -d, -f "linuxcnc|milltask" || true)
fi

# LinuxCNC version (best-effort)
LCNC_VERSION="unknown"
if have linuxcnc; then
    LCNC_VERSION=$(linuxcnc --version 2>&1 | head -1 || echo "unknown")
fi

# Mesa board reachability
MESA_REACHABLE="no"
if ping -c 1 -W 1 "$MESA_IP" >/dev/null 2>&1; then
    MESA_REACHABLE="yes"
fi

# mesaflash readhmid (short) — only if not colliding with a running LinuxCNC
MESA_HMID=""
if [[ "$LCNC_RUNNING" == "no" ]] && have mesaflash; then
    MESA_HMID=$(timeout 5 mesaflash --device 7i97 --addr "$MESA_IP" --readhmid 2>&1 | head -20 || true)
fi

# Real-time latency probe — read latest journal line from latency-test if any,
# otherwise skip. We do NOT launch latency-test here (it holds a core busy).
RT_LATENCY_NOTE=""
if have journalctl; then
    RT_LATENCY_NOTE=$(journalctl --since "24 hours ago" -g "latency" --no-pager 2>/dev/null | tail -1 || true)
fi

# halcmd snapshot — only if LinuxCNC is up
declare -A HAL_VALUES
HAL_SNAPSHOT_OK="no"
if [[ "$LCNC_RUNNING" == "yes" ]] && have halcmd; then
    HAL_SNAPSHOT_OK="yes"
    for sig in "${HAL_SIGNALS[@]}"; do
        # halcmd show sig <name> prints a table; grab the value column when present.
        val=$(halcmd -s show sig "$sig" 2>/dev/null | awk '$1 !~ /^Signals/ && NF>=2 {print $2; exit}')
        HAL_VALUES["$sig"]="${val:-unavailable}"
    done
fi

# Git repo hygiene
cd "$REPO_DIR" || { echo "repo dir $REPO_DIR missing"; exit 2; }
GIT_HEAD=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_HEAD_MSG=$(git log -1 --pretty=%s 2>/dev/null || echo "")
GIT_DIRTY_COUNT=$(git status --porcelain 2>/dev/null | grep -v "^.. status/host_status" | wc -l | tr -d ' ')

# ---------- write markdown ----------
mkdir -p "$STATUS_DIR"

{
  echo "# Mazak VQC 20/40 LinuxCNC Host Status"
  echo
  echo "_Auto-generated by \`scripts/host_status/collect_status.sh\` — do not edit by hand._"
  echo
  echo "**Reported:** $(ts_human) (UTC $(ts_iso))"
  echo
  echo "## Host"
  echo
  echo "| Field | Value |"
  echo "|---|---|"
  echo "| Hostname | \`$HOST\` |"
  echo "| OS | $OS_PRETTY |"
  echo "| Kernel | \`$KERNEL\` |"
  echo "| Uptime | $UPTIME |"
  echo "| Load avg (1/5/15) | $LOAD |"
  echo "| Memory | $MEM_LINE |"
  echo "| Disk (/) | $DISK_LINE |"
  echo
  echo "## LinuxCNC"
  echo
  echo "| Field | Value |"
  echo "|---|---|"
  echo "| Running | **$LCNC_RUNNING** |"
  echo "| Version | $LCNC_VERSION |"
  echo "| PIDs | \`${LCNC_PIDS:-—}\` |"
  echo "| HAL snapshot | $HAL_SNAPSHOT_OK |"
  if [[ -n "$RT_LATENCY_NOTE" ]]; then
    echo "| Latency note (24 h) | \`$(echo "$RT_LATENCY_NOTE" | tr '`' "'" )\` |"
  fi
  echo
  if [[ "$HAL_SNAPSHOT_OK" == "yes" ]]; then
    echo "### HAL signals"
    echo
    echo "| Signal | Value |"
    echo "|---|---|"
    for sig in "${HAL_SIGNALS[@]}"; do
        echo "| \`$sig\` | \`${HAL_VALUES[$sig]}\` |"
    done
    echo
  fi
  echo "## Mesa"
  echo
  echo "| Field | Value |"
  echo "|---|---|"
  echo "| Configured IP | \`$MESA_IP\` |"
  echo "| Ping reachable | **$MESA_REACHABLE** |"
  if [[ -n "$MESA_HMID" ]]; then
    echo
    echo "**\`mesaflash --readhmid\` (first 20 lines):**"
    echo
    echo '```'
    echo "$MESA_HMID"
    echo '```'
  fi
  echo
  echo "## Repository"
  echo
  echo "| Field | Value |"
  echo "|---|---|"
  echo "| Branch | \`$BRANCH\` |"
  echo "| HEAD | \`$GIT_HEAD\` — $GIT_HEAD_MSG |"
  echo "| Local uncommitted files (excluding status/) | $GIT_DIRTY_COUNT |"
} > "$MD_FILE"

# ---------- write json ----------
python3 - "$JSON_FILE" <<PY
import json, sys, os
data = {
    "reported_utc": "$(ts_iso)",
    "host": {
        "hostname": $(printf '%s' "$HOST" | json_escape),
        "os": $(printf '%s' "$OS_PRETTY" | json_escape),
        "kernel": $(printf '%s' "$KERNEL" | json_escape),
        "uptime": $(printf '%s' "$UPTIME" | json_escape),
        "loadavg": $(printf '%s' "$LOAD" | json_escape),
        "memory": $(printf '%s' "$MEM_LINE" | json_escape),
        "disk_root": $(printf '%s' "$DISK_LINE" | json_escape),
    },
    "linuxcnc": {
        "running": "$LCNC_RUNNING" == "yes",
        "version": $(printf '%s' "$LCNC_VERSION" | json_escape),
        "pids": $(printf '%s' "$LCNC_PIDS" | json_escape),
        "hal_snapshot_ok": "$HAL_SNAPSHOT_OK" == "yes",
        "hal_signals": {
$(for sig in "${HAL_SIGNALS[@]}"; do
    v="${HAL_VALUES[$sig]:-unavailable}"
    printf '            %s: %s,\n' "$(printf '%s' "$sig" | json_escape)" "$(printf '%s' "$v" | json_escape)"
done)
        },
    },
    "mesa": {
        "ip": $(printf '%s' "$MESA_IP" | json_escape),
        "reachable": "$MESA_REACHABLE" == "yes",
    },
    "repo": {
        "branch": $(printf '%s' "$BRANCH" | json_escape),
        "head": $(printf '%s' "$GIT_HEAD" | json_escape),
        "head_msg": $(printf '%s' "$GIT_HEAD_MSG" | json_escape),
        "dirty_files": int("$GIT_DIRTY_COUNT" or 0),
    },
}
with open(sys.argv[1], "w") as f:
    json.dump(data, f, indent=2, sort_keys=True)
    f.write("\n")
PY

# ---------- commit + push ----------
git add "$MD_FILE" "$JSON_FILE"

if git diff --cached --quiet; then
    echo "$(ts_human) no status changes"
    exit 0
fi

# Ensure identity is set for this commit path (fallback so systemd env doesn't drop it)
git -c user.name="LinuxCNC Host" -c user.email="linuxcnc-host@localhost" \
    commit -m "status: automated host status $(ts_iso)" >/dev/null

# Only push if the local branch is tracking a remote. Never force.
if git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
    git push --quiet
    echo "$(ts_human) pushed status"
else
    echo "$(ts_human) committed locally (no upstream configured)"
fi
